### ISSUE TITLE
F11 key doesn't work when using this card

### ISSUE THREAD

**Issue by sdrapha** [mathoudebine/homeassistant-browser-control-card#4]
F11 key doesn't work when using this card

Using Firefox 97.0.1 (64-bit)

**Comment by sdrapha** [comment]
A bit investigation I just started, I think that in all other views that doesn't have the card showing, the F11 is broken. If I do have this card showing in the actual view, it works.
Does the event listener managing happens out of the scope where this card is actually showing?

**Comment by mathoudebine** [comment]
Hi, thanks for raising the issue.

I made some tests on Firefox and Chrome and found that the event manager of the card to catch F11 press is not working as expected.
On Chrome and Firefox, the F11 key press start a specific full-screen experience that is different than the page full-screen from the card button. For Firefox for example, if you go to full-screen using F11 you can still have the address bar and tabs if you move your mouse to the top of the screen.

I will remove the event listener of the card, so that both full-screen modes (browser full-screen experience with F11, and page full-screen from card button) can be used based on user preference.
It will also solve your issue.
